/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CatalogMgr.java
 *
 * Created on 27 févr. 2012, 17:41:55
 */

package creawin;

import java.io.Writer;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import modele.Oeuvre;
import modele.Peinture;
import modele.Sculpture;
import service.Service;

/**
 *
 * @author Administrateur
 */
public class CatalogMgr extends javax.swing.JFrame {

    /** Creates new form CatalogMgr */
    public CatalogMgr() {
	
        initComponents();
	
	DefaultListModel listModel = new DefaultListModel();
	
	List<Oeuvre> catalog = Service.rechercherToutesLesOeuvres();
	for (Oeuvre o:catalog)
	{	    
	    listModel.addElement(o);
	}
	oeuvresList.setModel(listModel);
	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsPane = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        ReservBtn = new javax.swing.JButton();
        oeuvresSP = new javax.swing.JScrollPane();
        oeuvresList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        ReservBtn.setText("Voir les réservations");

        javax.swing.GroupLayout detailsPaneLayout = new javax.swing.GroupLayout(detailsPane);
        detailsPane.setLayout(detailsPaneLayout);
        detailsPaneLayout.setHorizontalGroup(
            detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPaneLayout.createSequentialGroup()
                .addGroup(detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailsPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReservBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPaneLayout.setVerticalGroup(
            detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPaneLayout.createSequentialGroup()
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReservBtn)
                .addGap(55, 55, 55))
        );

        oeuvresList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                oeuvresListValueChanged(evt);
            }
        });
        oeuvresSP.setViewportView(oeuvresList);

        jMenu1.setText("Aide");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quitter");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(oeuvresSP, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(oeuvresSP, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oeuvresListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_oeuvresListValueChanged
        String text = "Oeuvre : " + ((Oeuvre) this.oeuvresList.getSelectedValue()).getNom() + "\nArtiste : " + ((Oeuvre) this.oeuvresList.getSelectedValue()).getArtiste(); 
	text += "\nDescription : " + ((Oeuvre) this.oeuvresList.getSelectedValue()).getDescription() + "\n";
	
	if (this.oeuvresList.getSelectedValue().getClass() == Peinture.class)
	{
	    text += "Type : Peinture\nHauteur :" + ((Peinture) this.oeuvresList.getSelectedValue()).getHauteur(); 
	    text += "\nLargeur : " +((Peinture) this.oeuvresList.getSelectedValue()).getLargeur();
	}
	else
	{
	    text += "Type : Sculpture\nHauteur :" + ((Sculpture) this.oeuvresList.getSelectedValue()).getHauteur(); 
	    text += "\nLargeur : " +((Sculpture) this.oeuvresList.getSelectedValue()).getLargeur();
	    text += "\nEpaisseur : " +((Sculpture) this.oeuvresList.getSelectedValue()).getEpaisseur();
	}
	text += "\nTarif Journalier : " + ((Oeuvre) this.oeuvresList.getSelectedValue()).getTarifJournalier()+ " €";
	
	this.textArea1.setText(text);
    }//GEN-LAST:event_oeuvresListValueChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogMgr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReservBtn;
    private javax.swing.JPanel detailsPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JList oeuvresList;
    private javax.swing.JScrollPane oeuvresSP;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

}
